select * from customer limit 20 

-- total revenue generated by male vs female
select gender, SUM(purchase_amount) as revenue 
from customer 
group by gender

-- which customers used discount but still spent more than the average purchase amount
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

-- which are the top 5 products with highest average review rating
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Review"
from customer
group by item_purchased
order by avg(review_rating) desc 
limit 5;

-- compare the average purchase amounts between standard and express shipping
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type

-- do subscribed customers spend more, compare average spend and total revenue between subscribers and non subscribers
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

-- which 5 projects have the highest percent of purchase with discounts applied 
select item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*)) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- segment customers into new, returning, loyal based on total number of previous purchases and show count of each segments
with customer_type as (
select customer_id, previous_purchases,
CASE
WHEN previous_purchases = 1 THEN 'New'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
ELSE 'loyal'
END AS customer_segment
from customer
)
select customer_segment, count(*) as "Number of Customers"
from customer_type 
group by customer_segment